name: test and coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest-check-and-coverage:
    runs-on: ${{ matrix.config.os}}

    name: ${{ matrix.config.os }} (${{ matrix.config.python-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04, python-version: "3.6"}
          - {os: ubuntu-20.04, python-version: "3.8"}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # to deal with torch
          pip install .
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pip install .
          pytest
      - name: check location
        run: ls
      - name: check location 2
        run: ls
        working-directory: ./local_conformal
      - name: Save coverage only once
        if: runner.os == "Linux" & ${{matrix.python-verson == 3.6}}
        run: |
            pip install pytest
            pip install pytest-cov
            pip install ../.
            pytest --cov=local_conformal --cov-config=.coveragerc --cov-report=xml tests
        working-directory: ./local_conformal
      - name: Code coverage
        if: runner.os == "Linux" & ${{matrix.python-verson == 3.6}}
        uses: codecov/codecov-action@v1
        with:
          files: local_conformal/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Wemake Python Styleguide
        uses: wemake-services/wemake-python-styleguide@0.13.4
        continue-on-error: true
        with:
          reporter: 'github-pr-review'






