name: pytest check and code coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest-check-and-coverage:
    runs-on: ${{ matrix.config.os}}

    name: ${{ matrix.config.os }} (${{ matrix.config.python-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04, python-version: "3.6"}
          - {os: ubuntu-20.04, python-version: "3.8"}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install depedencies
        run: python -m pip install --upgrade pip
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pip install local_conformal/.
          pytest local_conformal/tests
      - name: Save coverage only once
        if: runner.os == "Linux" & ${{matrix.python-verson == 3.6}}
        run: |
            pip install pytest
            pip install pytest-cov
            pip install local_conformal/.
            pytest local_conformal/tests/ --cov=./ --cov-report=xml
      - name: Code coverage
        if: runner.os == "Linux" & ${{matrix.python-verson == 3.6}}
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml

      - name: lint
        run: |
          pip install pylint
          pip install .
          pylint local_conformal/*.py

      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.13.4
        continue-on-error: true
        with:
          reporter: 'github-pr-review'






